#!/bin/bash

STORAGE=".saves"

if [[ ! -d "$STORAGE" ]]; then
    mkdir $STORAGE
fi

python count.py $1 > blamesgohere
#diff --side-by-side --suppress-common-lines old out | less
cat blamesgohere

#inc counter if file already exists for same date
newfilename=$(date +%Y%m%d)
searchname=$newfilename
i="1"
while [[ -e $STORAGE/$searchname ]]; do
    searchname=$newfilename-$i
    i=$[$i+1]
done
newfilename=$searchname

cp $STORAGE/out $STORAGE/old
mv $STORAGE/out $STORAGE/$newfilename
echo "Saved as $newfilename"
