#!/bin/bash

STORAGE=".saves"

if [[ ! -d "$STORAGE" ]]; then
    mkdir $STORAGE
fi

python count.py $1
#diff --side-by-side --suppress-common-lines old out | less
newfilename=$(date +%Y%m%d)
cp $STORAGE/out $STORAGE/old
mv $STORAGE/out $STORAGE/$newfilename
echo "Saved as $newfilename"
